### ISSUE TITLE
Anchor links do not work

### ISSUE THREAD

**Issue by rene-haefliger** [CodyHouse/cd-floating-navigation-changelog#1]
If anchor links are used in the navigation, the navigation does not close.

**Comment by claudia-romano** [comment]
Hi there, when you click on a link you should be redirected to a new page where the menu is closed. Or is the content loaded without a redirect? If this is the case, then you can use the `closeModal` event to close the modal navigation.
```
function closeModal(element) {
  var event = new CustomEvent('closeModal');
  element.dispatchEvent(event);
};

var modal = document.getElementById('float-nav-modal');
// close navigation
closeModal(modal[0]);
```

Cheers

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you are still experiencing this issue. Cheers!
